version: "3.3"
services:
  validation-api-web:
    build: ./
    container_name: validation-api-web
    depends_on:
      - validation-api-db
    entrypoint: ["make", "wait-for-db", "run-prod"]
    environment:
      PORT: 80
      DATABASE_URL: "postgresql://validation-api:validation-api@validation-api-db:5432/validation-api"
    image: validation-api-web
    ports:
      - "8888:80"
  validation-api-db:
    container_name: validation-api-db
    environment:
      POSTGRES_USER: validation-api
      POSTGRES_PASSWORD: validation-api
      POSTGRES_DB: validation-api
    image: postgres:13.1-alpine
    ports:
      - "5555:5432"
    restart: always
  validation-api-dba:
    container_name: validation-api-dba
    image: adminer
    restart: always
    ports:
      - 5556:8080
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:

